import type { Metadata } from "next";
import "./globals.css";
import { GeistSans, GeistMono } from "geist/font";
import { AppProviders } from "../../packages/providers";
import { ThemeToggle } from "../../packages/components/General/ThemeToggle/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = storage.get('app-theme') || getSystemTheme();
                setThemeColors(theme, THEME_COLORS[theme]);
              } catch (e) {}
            `,
          }}
        />
        <AppProviders>
          {children}
          <ThemeToggle />
        </AppProviders>
      </body>
    </html>
  );
}
